services:
  agents_server:
    build:
      context: .
      dockerfile: Dockerfile
    container_name: zhihui_agents
    ports: # 宿主机端口:容器端口
      - "8010:8010" # runtime_sandbox_server prot
      - "8021:8021" # eqv agent_runtime prot
      - "8022:8022" # eqv fastapi_server prot
    env_file:
      - path: .env
        required: true

    # 核心配置：挂载 Docker Socket 和 Docker CLI
    volumes:
      # 挂载 Docker Socket，让容器内能与宿主机的 Docker 守护进程通信
      - /var/run/docker.sock:/var/run/docker.sock
      # 挂载 Docker CLI 工具，确保容器内有 docker 命令
      - /usr/bin/docker:/usr/bin/docker:ro